services:
  api:
    build: .
    ports:
      - "8080:8080"

    env_file:
      - .env

    depends_on:
      - postgres

  postgres:
    image: postgres:17

    environment:
      POSTGRES_USER: kishan
      POSTGRES_PASSWORD: kishan
      POSTGRES_DB: ecom

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
